In [1]:
import pandas

In [2]:
file_path = 'dds_datasets/dds_ch2_rollingsales/rollingsales_manhattan.xls'

In [3]:
xls = pandas.ExcelFile(file_path)

In [4]:
xls.sheet_names

['Manhattan']

In [5]:
data_frame = xls.parse('Manhattan')

In [6]:
data_frame.head()

,Manhattan Rolling Sales File. All Sales From August 2012 - August 2013.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Sales File as of 08/30/2013 Coop Sales Files ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Neighborhood Name 09/06/13, Descriptive Data i...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Building Class Category is based on Building C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APART\nMENT\nNUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE\nPRICE,SALE DATE
4,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1306,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2214693,2013-05-20 00:00:00

# 불필요한 로우 제거

In [7]:
df2 = data_frame.drop(range(4))
df2

,Manhattan Rolling Sales File. All Sales From August 2012 - August 2013.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
4,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1306,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2214693,2013-05-20 00:00:00
5,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1307,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1654656,2013-05-16 00:00:00
6,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1308,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1069162,2013-05-23 00:00:00
7,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1309,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1374637,2013-05-15 00:00:00
8,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1310,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1649565,2013-05-13 00:00:00
9,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1311,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1705568,2013-05-21 00:00:00
10,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1312,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2036500,2013-07-10 00:00:00
11,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1314,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2214693,2013-06-04 00:00:00
12,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1317,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2418343,2013-05-31 00:00:00
13,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1318,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2749275,2013-05-24 00:00:00
14,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1319,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2189237,2013-07-02 00:00:00
15,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1320,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2291062,2013-05-24 00:00:00
16,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1323,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1603743,2013-07-22 00:00:00
17,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1324,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2927468,2013-07-16 00:00:00
18,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1325,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,3640243,2013-07-12 00:00:00
19,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1328,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,3232943,2013-07-10 00:00:00
20,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1333,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,6898643,2013-07-12 00:00:00
21,1,ALPHABET CITY,,4,384,1401,,RK,229 EAST 2ND STREET,1A,...,0,0,1,0,0,2008,4,RK,360000,2013-06-13 00:00:00
22,1,ALPHABET CITY,03 THREE FAMILY HOMES,1,377,66,,C0,243 EAST 7TH STREET,,...,3,0,3,2381,3084,1899,1,C0,3150000,2013-03-06 00:00:00
23,1,ALPHABET CITY,04 TAX CLASS 1 CONDOS,1C,399,1102,,R6,238 EAST 4TH STREET,-,...,1,0,1,0,0,1955,1,R6,3450000,2013-03-27 00:00:00
24,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,374,1,,C7,303 EAST 4TH STREET,,...,8,2,10,1501,6929,1900,2,C7,0,2013-02-05 00:00:00
25,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,375,62,,C4,715 EAST 5TH STREET,,...,20,0,20,2426,9345,1900,2,C4,3650000,2012-09-06 00:00:00
26,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,376,30,,C4,274 EAST SEVENTH STREET,,...,13,0,13,2726,13002,1910,2,C4,895250,2012-10-25 00:00:00
27,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,384,25,,C4,241 EAST 2ND STREET,,...,10,0,10,1775,7095,1900,2,C4,0,2013-04-18 00:00:00
28,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,385,1,,C7,17 AVENUE B,,...,7,1,8,2093,5852,1997,2,C7,283,2013-04-18 00:00:00
29,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,391,55,,C4,309 EAST 8TH STREET,,...,17,0,17,2164,9071,1900,2,C4,3500000,2012-10-16 00:00:00
30,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,397,33,,C7,14 AVENUE B,,...,25,2,27,3574,18212,1925,2,C7,13185684,2013-01-31 00:00:00
31,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,398,52,,C7,174 EAST 2ND STREET,,...,9,1,10,2226,5250,1900,2,C7,0,2013-01-07 00:00:00
32,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,398,52,,C7,174 EAST 2ND STREET,,...,9,1,10,2226,5250,1900,2,C7,0,2012-10-26 00:00:00
33,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,398,53,,C7,170 EAST 2ND STREET,,...,36,3,39,4452,17664,1900,2,C7,0,2013-01-07 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27369,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1211,,R4,340 CABRINI BLVD.,303,...,1,0,1,0,0,2002,2,R4,810000,2012-08-07 00:00:00
27370,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1212,,R4,340 CABRINI BOULEVARD,401,...,1,0,1,0,0,2002,2,R4,612999,2013-07-31 00:00:00
27371,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2180,1274,,R4,736 WEST 187 STREET,601,...,1,0,1,0,0,2003,2,R4,590000,2012-10-15 00:00:00
27372,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2180,1281,,R4,736 WEST 187TH STREET,608,...,1,0,1,0,0,2003,2,R4,520000,2013-06-19 00:00:00
27373,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2180,1310,,R4,210 BENNETT AVENUE,2E,...,1,0,1,0,0,2008,2,R4,0,2012-08-15 00:00:00
27374,1,WASHINGTON HEIGHTS UPPER,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,2180,1103,,R1,114 BENNETT AVENUE,3A,...,1,0,1,0,0,2003,2,R1,10,2013-03-19 00:00:00
27375,1,WASHINGTON HEIGHTS UPPER,17 CONDOPS,2,2180,1007,,R9,1 BENNETT AVENUE,RES,...,65,0,65,11492,39762,1950,2,R9,11000000,2013-04-30 00:00:00
27376,1,WASHINGTON HEIGHTS UPPER,17 CONDOPS,2,2180,1007,,R9,"1 BENNETT AVENUE, RES",,...,0,0,0,0,0,1950,2,R9,11000000,2013-04-30 00:00:00
27377,1,WASHINGTON HEIGHTS UPPER,21 OFFICE BUILDINGS,4,2176,137,,O6,4249 BROADWAY,,...,0,1,1,2575,6825,1941,4,O6,3342996,2013-04-15 00:00:00
27378,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2158,65,,K1,1588 ST NICHOLAS AVENUE,,...,0,4,4,4488,4991,1960,4,K1,2550000,2012-11-09 00:00:00
27379,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2170,62,,K1,4452 BROADWAY,,...,0,4,4,7900,6438,1925,4,K1,7300000,2013-04-29 00:00:00
27380,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2170,70,,K2,4468-4470 BROADWAY,,...,0,7,7,10000,20000,1991,4,K2,1500000,2013-04-17 00:00:00
27381,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2174,32,,K1,65-71 SHERMAN AVENUE,,...,0,6,6,5000,5000,1927,4,K1,0,2013-05-07 00:00:00
27382,1,WASHINGTON HEIGHTS UPPER,27 FACTORIES,4,2246,28,,F9,290 DYCKMAN STREET,,...,0,1,1,17275,34570,1927,4,F9,5183000,2012-09-11 00:00:00
27383,1,WASHINGTON HEIGHTS UPPER,28 COMMERCIAL CONDOS,4,2180,1228,,RG,736 WEST 187 STREET,PRK28,...,0,0,1,0,0,2003,4,R5,17842,2012-10-15 00:00:00
27384,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,77,,G9,2430 AMSTERDAM AVENUE,,...,0,1,1,17925,5226,1935,4,G9,6000000,2013-05-30 00:00:00
27385,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,77,,G9,2430 AMSTERDAM AVENUE,,...,0,1,1,17925,5226,1935,4,G9,6000000,2013-01-31 00:00:00
27386,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,83,,G9,2420 AMSTERDAM AVENUE,,...,0,1,1,15000,2465,1971,4,G9,12000000,2013-05-30 00:00:00
27387,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2170,27,,G7,655 WEST 187 STREET,,...,0,0,0,1582,0,0,4,G7,0,2012-09-24 00:00:00
27388,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2170,28,,G7,657 WEST 187 STREET,,...,0,0,0,1582,0,0,4,G7,4750000,2012-09-24 00:00:00
27389,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2170,32,,G7,667 WEST 187 STREET,,...,0,0,0,4496,0,0,4,G7,0,2012-09-24 00:00:00
27390,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2246,43,,G1,270 DYCKMAN STREET,,...,0,2,2,14980,46200,1929,4,G1,4917000,2012-09-11 00:00:00
27391,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2155,89,,V1,2494 AMSTERDAM AVENUE,,...,0,0,0,3100,0,0,4,V1,690000,2013-01-29 00:00:00
27392,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2170,26,,V1,653 WEST 187TH STREET,,...,0,0,0,1582,0,0,4,V1,0,2013-04-22 00:00:00
27393,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2170,26,,V1,653 WEST 187 STREET,,...,0,0,0,1582,0,0,4,V1,185000,2012-08-23 00:00:00
27394,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2170,400,,V1,44 FAIRVIEW AVENUE,,...,0,0,0,16217,0,0,4,V1,0,2013-04-29 00:00:00
27395,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,75,,V1,BENNETT AVENUE,,...,0,0,0,4150,0,0,4,V1,495000,2013-06-26 00:00:00
27396,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,75,,V1,BENNETT AVENUE,,...,0,0,0,4150,0,0,4,V1,0,2013-04-02 00:00:00
27397,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,76,,V1,N/A MAGAW PLACE,,...,0,0,0,760,0,0,4,V1,0,2013-06-26 00:00:00
27398,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,76,,V1,MAGAW PLACE,,...,0,0,0,760,0,0,4,V1,0,2013-04-02 00:00:00

# 컬럼 이름 정리하기
- 네번째 row에 있는 값들이 컬럼 값인 것 같으니 바꿔치자

### 네번째 row 값 출력

In [8]:
list(data_frame.iloc[3].items())

[('Manhattan Rolling Sales File.  All Sales From August 2012 - August 2013. ',
  'BOROUGH'),
 ('Unnamed: 1', 'NEIGHBORHOOD'),
 ('Unnamed: 2', 'BUILDING CLASS CATEGORY'),
 ('Unnamed: 3', 'TAX CLASS AT PRESENT'),
 ('Unnamed: 4', 'BLOCK'),
 ('Unnamed: 5', 'LOT'),
 ('Unnamed: 6', 'EASE-MENT'),
 ('Unnamed: 7', 'BUILDING CLASS AT PRESENT'),
 ('Unnamed: 8', 'ADDRESS'),
 ('Unnamed: 9', 'APART\nMENT\nNUMBER'),
 ('Unnamed: 10', 'ZIP CODE'),
 ('Unnamed: 11', 'RESIDENTIAL UNITS'),
 ('Unnamed: 12', 'COMMERCIAL UNITS'),
 ('Unnamed: 13', 'TOTAL UNITS'),
 ('Unnamed: 14', 'LAND SQUARE FEET'),
 ('Unnamed: 15', 'GROSS SQUARE FEET'),
 ('Unnamed: 16', 'YEAR BUILT'),
 ('Unnamed: 17', 'TAX CLASS AT TIME OF SALE'),
 ('Unnamed: 18', 'BUILDING CLASS AT TIME OF SALE'),
 ('Unnamed: 19', 'SALE\nPRICE'),
 ('Unnamed: 20', 'SALE DATE')]

In [9]:
new_column_names = [v for k, v in data_frame.iloc[3].items()]

In [10]:
df2.columns

Index(['Manhattan Rolling Sales File.  All Sales From August 2012 - August 2013. ',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20'],
      dtype='object')

### 네번째 row 값와 현재 컬럼을 매핑

In [11]:
new_column_dict = dict(zip(df2.columns, new_column_names))
new_column_dict

{'Manhattan Rolling Sales File.  All Sales From August 2012 - August 2013. ': 'BOROUGH',
 'Unnamed: 1': 'NEIGHBORHOOD',
 'Unnamed: 10': 'ZIP CODE',
 'Unnamed: 11': 'RESIDENTIAL UNITS',
 'Unnamed: 12': 'COMMERCIAL UNITS',
 'Unnamed: 13': 'TOTAL UNITS',
 'Unnamed: 14': 'LAND SQUARE FEET',
 'Unnamed: 15': 'GROSS SQUARE FEET',
 'Unnamed: 16': 'YEAR BUILT',
 'Unnamed: 17': 'TAX CLASS AT TIME OF SALE',
 'Unnamed: 18': 'BUILDING CLASS AT TIME OF SALE',
 'Unnamed: 19': 'SALE\nPRICE',
 'Unnamed: 2': 'BUILDING CLASS CATEGORY',
 'Unnamed: 20': 'SALE DATE',
 'Unnamed: 3': 'TAX CLASS AT PRESENT',
 'Unnamed: 4': 'BLOCK',
 'Unnamed: 5': 'LOT',
 'Unnamed: 6': 'EASE-MENT',
 'Unnamed: 7': 'BUILDING CLASS AT PRESENT',
 'Unnamed: 8': 'ADDRESS',
 'Unnamed: 9': 'APART\nMENT\nNUMBER'}

### 업데이트

In [12]:
df3 = df2.rename(columns=new_column_dict)
df3

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APART MENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
4,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1306,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2214693,2013-05-20 00:00:00
5,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1307,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1654656,2013-05-16 00:00:00
6,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1308,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1069162,2013-05-23 00:00:00
7,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1309,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1374637,2013-05-15 00:00:00
8,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1310,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1649565,2013-05-13 00:00:00
9,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1311,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1705568,2013-05-21 00:00:00
10,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1312,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2036500,2013-07-10 00:00:00
11,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1314,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2214693,2013-06-04 00:00:00
12,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1317,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2418343,2013-05-31 00:00:00
13,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1318,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2749275,2013-05-24 00:00:00
14,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1319,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2189237,2013-07-02 00:00:00
15,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1320,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2291062,2013-05-24 00:00:00
16,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1323,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1603743,2013-07-22 00:00:00
17,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1324,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2927468,2013-07-16 00:00:00
18,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1325,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,3640243,2013-07-12 00:00:00
19,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1328,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,3232943,2013-07-10 00:00:00
20,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1333,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,6898643,2013-07-12 00:00:00
21,1,ALPHABET CITY,,4,384,1401,,RK,229 EAST 2ND STREET,1A,...,0,0,1,0,0,2008,4,RK,360000,2013-06-13 00:00:00
22,1,ALPHABET CITY,03 THREE FAMILY HOMES,1,377,66,,C0,243 EAST 7TH STREET,,...,3,0,3,2381,3084,1899,1,C0,3150000,2013-03-06 00:00:00
23,1,ALPHABET CITY,04 TAX CLASS 1 CONDOS,1C,399,1102,,R6,238 EAST 4TH STREET,-,...,1,0,1,0,0,1955,1,R6,3450000,2013-03-27 00:00:00
24,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,374,1,,C7,303 EAST 4TH STREET,,...,8,2,10,1501,6929,1900,2,C7,0,2013-02-05 00:00:00
25,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,375,62,,C4,715 EAST 5TH STREET,,...,20,0,20,2426,9345,1900,2,C4,3650000,2012-09-06 00:00:00
26,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,376,30,,C4,274 EAST SEVENTH STREET,,...,13,0,13,2726,13002,1910,2,C4,895250,2012-10-25 00:00:00
27,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,384,25,,C4,241 EAST 2ND STREET,,...,10,0,10,1775,7095,1900,2,C4,0,2013-04-18 00:00:00
28,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,385,1,,C7,17 AVENUE B,,...,7,1,8,2093,5852,1997,2,C7,283,2013-04-18 00:00:00
29,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,391,55,,C4,309 EAST 8TH STREET,,...,17,0,17,2164,9071,1900,2,C4,3500000,2012-10-16 00:00:00
30,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,397,33,,C7,14 AVENUE B,,...,25,2,27,3574,18212,1925,2,C7,13185684,2013-01-31 00:00:00
31,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,398,52,,C7,174 EAST 2ND STREET,,...,9,1,10,2226,5250,1900,2,C7,0,2013-01-07 00:00:00
32,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,398,52,,C7,174 EAST 2ND STREET,,...,9,1,10,2226,5250,1900,2,C7,0,2012-10-26 00:00:00
33,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,398,53,,C7,170 EAST 2ND STREET,,...,36,3,39,4452,17664,1900,2,C7,0,2013-01-07 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27369,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1211,,R4,340 CABRINI BLVD.,303,...,1,0,1,0,0,2002,2,R4,810000,2012-08-07 00:00:00
27370,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1212,,R4,340 CABRINI BOULEVARD,401,...,1,0,1,0,0,2002,2,R4,612999,2013-07-31 00:00:00
27371,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2180,1274,,R4,736 WEST 187 STREET,601,...,1,0,1,0,0,2003,2,R4,590000,2012-10-15 00:00:00
27372,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2180,1281,,R4,736 WEST 187TH STREET,608,...,1,0,1,0,0,2003,2,R4,520000,2013-06-19 00:00:00
27373,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2180,1310,,R4,210 BENNETT AVENUE,2E,...,1,0,1,0,0,2008,2,R4,0,2012-08-15 00:00:00
27374,1,WASHINGTON HEIGHTS UPPER,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,2180,1103,,R1,114 BENNETT AVENUE,3A,...,1,0,1,0,0,2003,2,R1,10,2013-03-19 00:00:00
27375,1,WASHINGTON HEIGHTS UPPER,17 CONDOPS,2,2180,1007,,R9,1 BENNETT AVENUE,RES,...,65,0,65,11492,39762,1950,2,R9,11000000,2013-04-30 00:00:00
27376,1,WASHINGTON HEIGHTS UPPER,17 CONDOPS,2,2180,1007,,R9,"1 BENNETT AVENUE, RES",,...,0,0,0,0,0,1950,2,R9,11000000,2013-04-30 00:00:00
27377,1,WASHINGTON HEIGHTS UPPER,21 OFFICE BUILDINGS,4,2176,137,,O6,4249 BROADWAY,,...,0,1,1,2575,6825,1941,4,O6,3342996,2013-04-15 00:00:00
27378,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2158,65,,K1,1588 ST NICHOLAS AVENUE,,...,0,4,4,4488,4991,1960,4,K1,2550000,2012-11-09 00:00:00
27379,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2170,62,,K1,4452 BROADWAY,,...,0,4,4,7900,6438,1925,4,K1,7300000,2013-04-29 00:00:00
27380,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2170,70,,K2,4468-4470 BROADWAY,,...,0,7,7,10000,20000,1991,4,K2,1500000,2013-04-17 00:00:00
27381,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2174,32,,K1,65-71 SHERMAN AVENUE,,...,0,6,6,5000,5000,1927,4,K1,0,2013-05-07 00:00:00
27382,1,WASHINGTON HEIGHTS UPPER,27 FACTORIES,4,2246,28,,F9,290 DYCKMAN STREET,,...,0,1,1,17275,34570,1927,4,F9,5183000,2012-09-11 00:00:00
27383,1,WASHINGTON HEIGHTS UPPER,28 COMMERCIAL CONDOS,4,2180,1228,,RG,736 WEST 187 STREET,PRK28,...,0,0,1,0,0,2003,4,R5,17842,2012-10-15 00:00:00
27384,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,77,,G9,2430 AMSTERDAM AVENUE,,...,0,1,1,17925,5226,1935,4,G9,6000000,2013-05-30 00:00:00
27385,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,77,,G9,2430 AMSTERDAM AVENUE,,...,0,1,1,17925,5226,1935,4,G9,6000000,2013-01-31 00:00:00
27386,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,83,,G9,2420 AMSTERDAM AVENUE,,...,0,1,1,15000,2465,1971,4,G9,12000000,2013-05-30 00:00:00
27387,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2170,27,,G7,655 WEST 187 STREET,,...,0,0,0,1582,0,0,4,G7,0,2012-09-24 00:00:00
27388,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2170,28,,G7,657 WEST 187 STREET,,...,0,0,0,1582,0,0,4,G7,4750000,2012-09-24 00:00:00
27389,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2170,32,,G7,667 WEST 187 STREET,,...,0,0,0,4496,0,0,4,G7,0,2012-09-24 00:00:00
27390,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2246,43,,G1,270 DYCKMAN STREET,,...,0,2,2,14980,46200,1929,4,G1,4917000,2012-09-11 00:00:00
27391,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2155,89,,V1,2494 AMSTERDAM AVENUE,,...,0,0,0,3100,0,0,4,V1,690000,2013-01-29 00:00:00
27392,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2170,26,,V1,653 WEST 187TH STREET,,...,0,0,0,1582,0,0,4,V1,0,2013-04-22 00:00:00
27393,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2170,26,,V1,653 WEST 187 STREET,,...,0,0,0,1582,0,0,4,V1,185000,2012-08-23 00:00:00
27394,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2170,400,,V1,44 FAIRVIEW AVENUE,,...,0,0,0,16217,0,0,4,V1,0,2013-04-29 00:00:00
27395,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,75,,V1,BENNETT AVENUE,,...,0,0,0,4150,0,0,4,V1,495000,2013-06-26 00:00:00
27396,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,75,,V1,BENNETT AVENUE,,...,0,0,0,4150,0,0,4,V1,0,2013-04-02 00:00:00
27397,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,76,,V1,N/A MAGAW PLACE,,...,0,0,0,760,0,0,4,V1,0,2013-06-26 00:00:00
27398,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,76,,V1,MAGAW PLACE,,...,0,0,0,760,0,0,4,V1,0,2013-04-02 00:00:00

In [13]:
df3.sort_values(by=['SALE DATE'])

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APART MENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
16553,1,MURRAY HILL,10 COOPS - ELEVATOR APARTMENTS,2,892,25,,D4,"137 EAST 36 STREET, 23K",,...,0,0,0,0,0,1966,2,D4,792500,2012-08-01 00:00:00
13008,1,MIDTOWN WEST,10 COOPS - ELEVATOR APARTMENTS,2,1011,52,,D4,"150 CENTRAL PARK SOUTH, 2103",,...,0,0,0,0,0,1940,2,D4,0,2012-08-01 00:00:00
9047,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1346,49,,D4,"300 EAST 54TH STREET, 2H",,...,0,0,0,0,0,1977,2,D4,715000,2012-08-01 00:00:00
27211,1,WASHINGTON HEIGHTS UPPER,10 COOPS - ELEVATOR APARTMENTS,2,2179,489,,D4,"360 CABRINI BLVD., 4H",,...,0,0,0,0,0,1942,2,D4,300000,2012-08-01 00:00:00
25249,1,UPPER WEST SIDE (79-96),07 RENTALS - WALKUP APARTMENTS,2B,1229,35,,C7,452 AMSTERDAM AVENUE,,...,8,2,10,2175,9250,1900,2,C7,0,2012-08-01 00:00:00
16084,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1726,,RH,870 7 AVENUE,225,...,0,0,1,0,0,1925,4,R5,13047,2012-08-01 00:00:00
8989,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1341,1,,D4,"301 EAST 48TH STREET, 15C",,...,0,0,0,0,0,1964,2,D4,1325000,2012-08-01 00:00:00
24703,1,UPPER WEST SIDE (59-79),13 CONDOS - ELEVATOR APARTMENTS,2,1171,3178,,R4,120 RIVERSIDE BOULEVARD,11M,...,1,0,1,0,0,0,2,R4,765000,2012-08-01 00:00:00
18849,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1397,4,,D4,"565 PARK AVENUE, 11E",,...,0,0,0,0,0,1913,2,D4,2100000,2012-08-01 00:00:00
7094,1,INWOOD,13 CONDOS - ELEVATOR APARTMENTS,2,2221,1113,,R4,571 ACADEMY STREET,2A,...,1,0,1,0,0,0,2,R4,365000,2012-08-01 00:00:00
9771,1,MIDTOWN EAST,13 CONDOS - ELEVATOR APARTMENTS,2,1341,1861,,R4,865 1 AVENUE,12E,...,1,0,1,0,0,0,2,R4,790000,2012-08-01 00:00:00
1976,1,CLINTON,13 CONDOS - ELEVATOR APARTMENTS,2,1071,1218,,R4,500 WEST 43RD STREET,27B,...,1,0,1,0,0,1988,2,R4,800000,2012-08-01 00:00:00
6535,1,HARLEM-EAST,07 RENTALS - WALKUP APARTMENTS,2B,1796,3,,C4,2326 SECOND AVE,,...,6,1,7,1875,5500,1900,2,C4,0,2012-08-01 00:00:00
6530,1,HARLEM-EAST,07 RENTALS - WALKUP APARTMENTS,2B,1716,47,,C1,504 E 118TH STREET,,...,10,0,10,2523,8175,1910,2,C1,10,2012-08-01 00:00:00
16085,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1726,,RH,870 7 AVENUE,225,...,0,0,1,0,0,1925,4,R5,13047,2012-08-01 00:00:00
5230,1,GREENWICH VILLAGE-WEST,10 COOPS - ELEVATOR APARTMENTS,2,620,19,,D4,"350 BLEECKER STREET, 3A",,...,0,0,0,0,0,1962,2,D4,433500,2012-08-01 00:00:00
16086,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1726,,RH,870 7 AVENUE,225,...,0,0,1,0,0,1925,4,R5,20080,2012-08-01 00:00:00
6499,1,HARLEM-EAST,07 RENTALS - WALKUP APARTMENTS,2A,1665,9,,C3,217 E 115TH STREET,,...,4,0,4,1817,2697,1910,2,C3,10,2012-08-01 00:00:00
16087,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1726,,RH,870 7 AVENUE,225,...,0,0,1,0,0,1925,4,R5,13047,2012-08-01 00:00:00
23898,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1185,19,,D4,"325 WEST END AVENUE, 3D",,...,0,0,0,0,0,1916,2,D4,4425000,2012-08-01 00:00:00
25670,1,UPPER WEST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1239,56,,D4,"288-290 WEST 92ND STREET, 3E",,...,0,0,0,0,0,1940,2,D4,465000,2012-08-01 00:00:00
24960,1,UPPER WEST SIDE (59-79),17 CONDOPS,2,1158,1107,,R9,"180 WEST END AVENUE, 3-R",,...,0,0,0,0,0,1965,2,R9,597500,2012-08-01 00:00:00
15727,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1141,,RH,870 7 AVENUE,TIM16,...,0,0,1,0,0,0,4,R5,100,2012-08-01 00:00:00
5475,1,GREENWICH VILLAGE-WEST,13 CONDOS - ELEVATOR APARTMENTS,2,629,1312,,R4,77 8 AVENUE,502,...,1,0,1,0,0,0,2,R4,0,2012-08-01 00:00:00
24699,1,UPPER WEST SIDE (59-79),13 CONDOS - ELEVATOR APARTMENTS,2,1171,3169,,R4,120 RIVERSIDE BOULEVARD,15L,...,1,0,1,0,0,0,2,R4,0,2012-08-01 00:00:00
15797,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1198,,RH,200 WEST 56TH STREET,,...,0,0,1,0,0,0,4,R5,10040,2012-08-01 00:00:00
22091,1,UPPER EAST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1576,1,,D4,"501 EAST 79TH STREET, 11F",,...,0,0,0,0,0,1960,2,D4,930000,2012-08-01 00:00:00
25248,1,UPPER WEST SIDE (79-96),07 RENTALS - WALKUP APARTMENTS,2B,1229,34,,C7,450 AMSTERDAM AVENUE,,...,8,2,10,2175,9250,1910,2,C7,12375000,2012-08-01 00:00:00
25694,1,UPPER WEST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1243,8,,D4,"255 WEST 95TH STREET, 2A",,...,0,0,0,0,0,1908,2,D4,740000,2012-08-01 00:00:00
17171,1,SOHO,09 COOPS - WALKUP APARTMENTS,2,517,7,,C6,"145 SULLIVAN STREET, 1A",,...,0,0,0,0,0,1910,2,C6,405000,2012-08-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23017,1,UPPER EAST SIDE (96-110),10 COOPS - ELEVATOR APARTMENTS,2,1604,1,,D4,"1170 FIFTH AVENUE, 2B",,...,0,0,0,0,0,1926,2,D4,3650000,2013-08-15 00:00:00
27259,1,WASHINGTON HEIGHTS UPPER,10 COOPS - ELEVATOR APARTMENTS,2,2180,450,,D4,"100 OVERLOOK TERRACE, 617",,...,0,0,0,0,0,1963,2,D4,333000,2013-08-15 00:00:00
21360,1,UPPER EAST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1503,38,,D4,"1150 PARK AVENUE, 17F",,...,0,0,0,0,0,1940,2,D4,2325000,2013-08-15 00:00:00
23533,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1125,25,,D4,"1 WEST 72ND STREET, 17S",,...,0,0,0,0,0,1900,2,D4,3900000,2013-08-15 00:00:00
6851,1,HARLEM-UPPER,09 COOPS - WALKUP APARTMENTS,2,2066,51,,C6,"450 WEST 152 STREET, 24",,...,0,0,0,0,0,1906,2,C6,135540,2013-08-15 00:00:00
19339,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1439,1,,D4,"301 EAST 64TH STREET, 11K",,...,0,0,0,0,0,1963,2,D4,372500,2013-08-15 00:00:00
16615,1,MURRAY HILL,10 COOPS - ELEVATOR APARTMENTS,2,894,1,,D4,"67 PARK AVENUE, 11E",,...,0,0,0,0,0,1922,2,D4,615000,2013-08-15 00:00:00
7012,1,INWOOD,10 COOPS - ELEVATOR APARTMENTS,2,2238,1,,D4,"675 ACADEMY STREET, 2J",,...,0,0,0,0,0,1952,2,D4,390000,2013-08-15 00:00:00
19462,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1447,19,,D4,"353 EAST 72ND STREET, 10D",,...,0,0,0,0,0,1975,2,D4,475000,2013-08-15 00:00:00
22104,1,UPPER EAST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1576,5,,D4,"505 EAST 79TH STREET, 9B",,...,0,0,0,0,0,1963,2,D4,1875000,2013-08-15 00:00:00
19641,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1472,14,,D4,"435 EAST 77TH STREET, 12D",,...,0,0,0,0,0,1962,2,D4,367500,2013-08-15 00:00:00
4122,1,GRAMERCY,17 CONDOPS,2,874,1003,,R9,"157 EAST 18TH STREET, 5J",,...,0,0,0,0,0,0,2,R9,660000,2013-08-15 00:00:00
21131,1,UPPER EAST SIDE (79-96),09 COOPS - WALKUP APARTMENTS,2,1562,38,,C6,"416 EAST 83RD STREET, 2A",,...,0,0,0,0,0,1930,2,C6,292500,2013-08-15 00:00:00
22814,1,UPPER EAST SIDE (79-96),15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,1513,1603,,R1,157 EAST 84TH STREET,2,...,1,0,1,0,0,0,2,R1,8850000,2013-08-16 00:00:00
1411,1,CIVIC CENTER,10 COOPS - ELEVATOR APARTMENTS,2,117,1,,D4,"165 PARK ROW, 2F",,...,0,0,0,0,0,1960,2,D4,856000,2013-08-16 00:00:00
23543,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1126,14,,D4,"23 WEST 73RD STREET, 1111",,...,0,0,0,0,0,1926,2,D4,825000,2013-08-16 00:00:00
25047,1,UPPER WEST SIDE (59-79),17 CONDOPS,2,1158,1405,,R9,"170 WEST END AVENUE, PSR-19",,...,0,0,0,0,0,1965,2,R9,60000,2013-08-16 00:00:00
26804,1,UPPER WEST SIDE (96-116),17 CONDOPS,2,1883,1002,,R9,"545 WEST 111TH STREET, 6N",,...,0,0,0,0,0,1930,2,R9,399000,2013-08-16 00:00:00
20543,1,UPPER EAST SIDE (59-79),13 CONDOS - ELEVATOR APARTMENTS,2,1484,1125,,R4,515 EAST 72ND STREET,11E,...,1,0,1,0,0,1985,2,R4,692410,2013-08-16 00:00:00
9259,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1365,20,,D4,"60 SUTTON PLACE SOUTH, 5LS",,...,0,0,0,0,0,1951,2,D4,365000,2013-08-16 00:00:00
524,1,CHELSEA,10 COOPS - ELEVATOR APARTMENTS,2,797,76,,D4,"166 WEST 22ND STREET, 2A",,...,0,0,0,0,0,1950,2,D4,749000,2013-08-16 00:00:00
9260,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1365,20,,D4,"60 SUTTON PLACE SOUTH, 3BN",,...,0,0,0,0,0,1951,2,D4,815000,2013-08-19 00:00:00
3559,1,FLATIRON,17 CONDOPS,2,821,1202,,R9,"32 WEST 20TH STREET, 6N",,...,0,0,0,0,0,1912,2,R9,2199000,2013-08-19 00:00:00
13045,1,MIDTOWN WEST,10 COOPS - ELEVATOR APARTMENTS,2,1030,29,,D4,"200 CENTRAL PARK SOUTH, 5B",,...,0,0,0,0,0,1963,2,D4,4350000,2013-08-19 00:00:00
20806,1,UPPER EAST SIDE (59-79),17 CONDOPS,2,1458,1202,,R9,"420 EAST 64 STREET, W 10K",,...,0,0,0,0,0,0,2,R9,467896,2013-08-19 00:00:00
4585,1,GREENWICH VILLAGE-CENTRAL,10 COOPS - ELEVATOR APARTMENTS,2,576,1,,D4,"79 WEST 12TH STREET, 2B",,...,0,0,0,0,0,1960,2,D4,655000,2013-08-20 00:00:00
12628,1,MIDTOWN WEST,,4,1027,1721,,RH,870 7 AVENUE,220,...,0,0,1,0,0,1925,4,RH,0,2013-08-21 00:00:00
18978,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1406,50,,D4,"160 EAST 72ND STREET, 5 FLR",,...,0,0,0,0,0,1928,2,D4,8678250,2013-08-21 00:00:00
22388,1,UPPER EAST SIDE (79-96),13 CONDOS - ELEVATOR APARTMENTS,,1517,1169,,,141 EAST 88TH STREET,,...,0,0,0,0,0,0,2,R4,8527106,2013-08-23 00:00:00
22452,1,UPPER EAST SIDE (79-96),13 CONDOS - ELEVATOR APARTMENTS,2,1527,1134,,R4,215 EAST 81ST STREET,7F,...,1,0,1,0,0,0,2,R4,585000,2013-08-23 00:00:00

In [41]:
df3.keys()

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APART\nMENT\nNUMBER',
       'ZIP CODE', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE\nPRICE', 'SALE DATE'],
      dtype='object')

In [47]:
df4 = df3[df3['SALE\nPRICE']!=0]
df4

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APART MENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
4,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1306,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2214693,2013-05-20 00:00:00
5,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1307,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1654656,2013-05-16 00:00:00
6,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1308,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1069162,2013-05-23 00:00:00
7,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1309,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1374637,2013-05-15 00:00:00
8,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1310,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1649565,2013-05-13 00:00:00
9,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1311,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1705568,2013-05-21 00:00:00
10,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1312,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2036500,2013-07-10 00:00:00
11,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1314,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2214693,2013-06-04 00:00:00
12,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1317,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2418343,2013-05-31 00:00:00
13,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1318,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2749275,2013-05-24 00:00:00
14,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1319,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2189237,2013-07-02 00:00:00
15,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1320,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2291062,2013-05-24 00:00:00
16,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1323,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,1603743,2013-07-22 00:00:00
17,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1324,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,2927468,2013-07-16 00:00:00
18,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1325,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,3640243,2013-07-12 00:00:00
19,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1328,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,3232943,2013-07-10 00:00:00
20,1,,13 CONDOS - ELEVATOR APARTMENTS,,738,1333,,,345 WEST 14TH STREET,,...,0,0,0,0,0,0,2,R4,6898643,2013-07-12 00:00:00
21,1,ALPHABET CITY,,4,384,1401,,RK,229 EAST 2ND STREET,1A,...,0,0,1,0,0,2008,4,RK,360000,2013-06-13 00:00:00
22,1,ALPHABET CITY,03 THREE FAMILY HOMES,1,377,66,,C0,243 EAST 7TH STREET,,...,3,0,3,2381,3084,1899,1,C0,3150000,2013-03-06 00:00:00
23,1,ALPHABET CITY,04 TAX CLASS 1 CONDOS,1C,399,1102,,R6,238 EAST 4TH STREET,-,...,1,0,1,0,0,1955,1,R6,3450000,2013-03-27 00:00:00
25,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,375,62,,C4,715 EAST 5TH STREET,,...,20,0,20,2426,9345,1900,2,C4,3650000,2012-09-06 00:00:00
26,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,376,30,,C4,274 EAST SEVENTH STREET,,...,13,0,13,2726,13002,1910,2,C4,895250,2012-10-25 00:00:00
28,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,385,1,,C7,17 AVENUE B,,...,7,1,8,2093,5852,1997,2,C7,283,2013-04-18 00:00:00
29,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,391,55,,C4,309 EAST 8TH STREET,,...,17,0,17,2164,9071,1900,2,C4,3500000,2012-10-16 00:00:00
30,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,397,33,,C7,14 AVENUE B,,...,25,2,27,3574,18212,1925,2,C7,13185684,2013-01-31 00:00:00
34,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,398,53,,C7,170 EAST 2ND STREET,,...,36,3,39,4452,17664,1900,2,C7,3810602,2012-10-26 00:00:00
35,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,400,56,,C4,203 EAST 4TH STREET,,...,10,1,10,2404,6975,1900,2,C4,7333333,2013-04-09 00:00:00
36,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,400,57,,C4,201 EAST 4TH STREET,,...,9,1,9,2404,6875,1900,2,C4,7333333,2013-04-09 00:00:00
37,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,400,58,,C4,199 EAST 4TH STREET,,...,9,1,10,2404,7110,1900,2,C4,7333333,2013-04-09 00:00:00
38,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,400,60,,C4,195 EAST FOURTH STREET,,...,18,2,18,2404,8975,1913,2,C4,7000000,2013-04-09 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27314,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2164,1015,,R4,4260 BROADWAY,104,...,1,0,1,0,0,0,2,R4,4300000,2013-02-27 00:00:00
27320,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2164,1034,,R4,4260 BROADWAY,304,...,1,0,1,0,0,0,2,R4,365000,2013-03-07 00:00:00
27349,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2164,1098,,R4,160 WADSWORTH AVENUE,309,...,1,0,1,0,0,0,2,R4,195000,2013-06-04 00:00:00
27350,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2164,1103,,R4,160 WADSWORTH AVENUE,403,...,1,0,1,0,0,0,2,R4,336666,2013-05-08 00:00:00
27360,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2164,1119,,R4,160 WADSWORTH AVENUE,509,...,1,0,1,0,0,0,2,R4,200000,2013-07-15 00:00:00
27361,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2164,1122,,R4,160 WADSWORTH AVENUE,602,...,1,0,1,0,0,0,2,R4,349000,2013-06-26 00:00:00
27366,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1048,,R4,255 CABRINI BOULEVARD,5E,...,1,0,1,0,0,1987,2,R4,320000,2013-06-17 00:00:00
27367,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1057,,R4,255 CABRINI BOULEVARD,6F,...,1,0,1,0,0,1987,2,R4,240000,2012-12-28 00:00:00
27368,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1079,,R4,255 CABRINI BOULEVARD,4J,...,1,0,1,0,0,1987,2,R4,390000,2012-08-14 00:00:00
27369,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1211,,R4,340 CABRINI BLVD.,303,...,1,0,1,0,0,2002,2,R4,810000,2012-08-07 00:00:00
27370,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2179,1212,,R4,340 CABRINI BOULEVARD,401,...,1,0,1,0,0,2002,2,R4,612999,2013-07-31 00:00:00
27371,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2180,1274,,R4,736 WEST 187 STREET,601,...,1,0,1,0,0,2003,2,R4,590000,2012-10-15 00:00:00
27372,1,WASHINGTON HEIGHTS UPPER,13 CONDOS - ELEVATOR APARTMENTS,2,2180,1281,,R4,736 WEST 187TH STREET,608,...,1,0,1,0,0,2003,2,R4,520000,2013-06-19 00:00:00
27374,1,WASHINGTON HEIGHTS UPPER,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,2180,1103,,R1,114 BENNETT AVENUE,3A,...,1,0,1,0,0,2003,2,R1,10,2013-03-19 00:00:00
27375,1,WASHINGTON HEIGHTS UPPER,17 CONDOPS,2,2180,1007,,R9,1 BENNETT AVENUE,RES,...,65,0,65,11492,39762,1950,2,R9,11000000,2013-04-30 00:00:00
27376,1,WASHINGTON HEIGHTS UPPER,17 CONDOPS,2,2180,1007,,R9,"1 BENNETT AVENUE, RES",,...,0,0,0,0,0,1950,2,R9,11000000,2013-04-30 00:00:00
27377,1,WASHINGTON HEIGHTS UPPER,21 OFFICE BUILDINGS,4,2176,137,,O6,4249 BROADWAY,,...,0,1,1,2575,6825,1941,4,O6,3342996,2013-04-15 00:00:00
27378,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2158,65,,K1,1588 ST NICHOLAS AVENUE,,...,0,4,4,4488,4991,1960,4,K1,2550000,2012-11-09 00:00:00
27379,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2170,62,,K1,4452 BROADWAY,,...,0,4,4,7900,6438,1925,4,K1,7300000,2013-04-29 00:00:00
27380,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,2170,70,,K2,4468-4470 BROADWAY,,...,0,7,7,10000,20000,1991,4,K2,1500000,2013-04-17 00:00:00
27382,1,WASHINGTON HEIGHTS UPPER,27 FACTORIES,4,2246,28,,F9,290 DYCKMAN STREET,,...,0,1,1,17275,34570,1927,4,F9,5183000,2012-09-11 00:00:00
27383,1,WASHINGTON HEIGHTS UPPER,28 COMMERCIAL CONDOS,4,2180,1228,,RG,736 WEST 187 STREET,PRK28,...,0,0,1,0,0,2003,4,R5,17842,2012-10-15 00:00:00
27384,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,77,,G9,2430 AMSTERDAM AVENUE,,...,0,1,1,17925,5226,1935,4,G9,6000000,2013-05-30 00:00:00
27385,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,77,,G9,2430 AMSTERDAM AVENUE,,...,0,1,1,17925,5226,1935,4,G9,6000000,2013-01-31 00:00:00
27386,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2152,83,,G9,2420 AMSTERDAM AVENUE,,...,0,1,1,15000,2465,1971,4,G9,12000000,2013-05-30 00:00:00
27388,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2170,28,,G7,657 WEST 187 STREET,,...,0,0,0,1582,0,0,4,G7,4750000,2012-09-24 00:00:00
27390,1,WASHINGTON HEIGHTS UPPER,29 COMMERCIAL GARAGES,4,2246,43,,G1,270 DYCKMAN STREET,,...,0,2,2,14980,46200,1929,4,G1,4917000,2012-09-11 00:00:00
27391,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2155,89,,V1,2494 AMSTERDAM AVENUE,,...,0,0,0,3100,0,0,4,V1,690000,2013-01-29 00:00:00
27393,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2170,26,,V1,653 WEST 187 STREET,,...,0,0,0,1582,0,0,4,V1,185000,2012-08-23 00:00:00
27395,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,2180,75,,V1,BENNETT AVENUE,,...,0,0,0,4150,0,0,4,V1,495000,2013-06-26 00:00:00

In [48]:
dir(df4['SALE DATE'].dt)

['__bytes__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_add_delegate_accessors',
 '_constructor',
 '_delegate_method',
 '_delegate_property_get',
 '_delegate_property_set',
 '_dir_additions',
 '_dir_deletions',
 '_freeze',
 '_reset_cache',
 'ceil',
 'date',
 'day',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'floor',
 'freq',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'microsecond',
 'minute',
 'month',
 'nanosecond',
 'normalize',
 'quarter',
 'round',
 'second',
 'strftime',
 'time',
 'to_period',
 'to_pydatetime',
 'tz',
 'tz_convert',
 'tz_localize',
 'week',
 'weekday',
 'weekday_name',
 'weekofyear',
 'year']

In [49]:
df4.sort_values(by=['SALE DATE'])

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APART MENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
3514,1,FLATIRON,13 CONDOS - ELEVATOR APARTMENTS,2,856,1225,,R4,225 FIFTH AVENUE,9D,...,1,0,1,0,0,1900,2,R4,1666000,2012-08-01 00:00:00
18751,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1391,31,,D4,"65 EAST 76TH STREET, 10C",,...,0,0,0,0,0,1949,2,D4,814500,2012-08-01 00:00:00
15726,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1141,,RH,870 7 AVENUE,TIM16,...,0,0,1,0,0,0,4,R5,18067,2012-08-01 00:00:00
15727,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1141,,RH,870 7 AVENUE,TIM16,...,0,0,1,0,0,0,4,R5,100,2012-08-01 00:00:00
5196,1,GREENWICH VILLAGE-WEST,10 COOPS - ELEVATOR APARTMENTS,2,609,1,,D4,"175 WEST 13TH STREET, 3D",,...,0,0,0,0,0,1961,2,D4,1575000,2012-08-01 00:00:00
19117,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1413,64,,D4,"120 EAST 79 STREET, 10D",,...,0,0,0,0,0,1947,2,D4,612500,2012-08-01 00:00:00
16553,1,MURRAY HILL,10 COOPS - ELEVATOR APARTMENTS,2,892,25,,D4,"137 EAST 36 STREET, 23K",,...,0,0,0,0,0,1966,2,D4,792500,2012-08-01 00:00:00
23407,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1119,50,,D4,"50 WEST 67 STREET, 7B",,...,0,0,0,0,0,1917,2,D4,1650000,2012-08-01 00:00:00
23406,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1119,50,,D4,"50 WEST 67TH STREET, 7A",,...,0,0,0,0,0,1917,2,D4,1125000,2012-08-01 00:00:00
4906,1,GREENWICH VILLAGE-CENTRAL,22 STORE BUILDINGS,4,562,27,,K2,795 BROADWAY,,...,0,2,2,1875,3524,1927,4,K2,5000035,2012-08-01 00:00:00
16660,1,MURRAY HILL,10 COOPS - ELEVATOR APARTMENTS,2,916,9,,D4,"211 EAST 35TH ST, 7E",,...,0,0,0,0,0,1929,2,D4,699000,2012-08-01 00:00:00
5230,1,GREENWICH VILLAGE-WEST,10 COOPS - ELEVATOR APARTMENTS,2,620,19,,D4,"350 BLEECKER STREET, 3A",,...,0,0,0,0,0,1962,2,D4,433500,2012-08-01 00:00:00
16083,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1726,,RH,870 7 AVENUE,225,...,0,0,1,0,0,1925,4,R5,20080,2012-08-01 00:00:00
17945,1,TRIBECA,13 CONDOS - ELEVATOR APARTMENTS,2,132,1115,,R4,275 GREENWICH STREET,10BS,...,1,0,1,0,0,1987,2,R4,865000,2012-08-01 00:00:00
4469,1,GREENWICH VILLAGE-CENTRAL,10 COOPS - ELEVATOR APARTMENTS,2,564,54,,D4,"77 EAST 12 STREET, 16D",,...,0,0,0,0,0,1963,2,D4,662500,2012-08-01 00:00:00
24960,1,UPPER WEST SIDE (59-79),17 CONDOPS,2,1158,1107,,R9,"180 WEST END AVENUE, 3-R",,...,0,0,0,0,0,1965,2,R9,597500,2012-08-01 00:00:00
24349,1,UPPER WEST SIDE (59-79),13 CONDOS - ELEVATOR APARTMENTS,2,1150,1194,,R4,130 WEST 79TH STREET,19B,...,1,0,1,0,0,1987,2,R4,2500000,2012-08-01 00:00:00
23898,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1185,19,,D4,"325 WEST END AVENUE, 3D",,...,0,0,0,0,0,1916,2,D4,4425000,2012-08-01 00:00:00
16084,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1726,,RH,870 7 AVENUE,225,...,0,0,1,0,0,1925,4,R5,13047,2012-08-01 00:00:00
16085,1,MIDTOWN WEST,28 COMMERCIAL CONDOS,4,1027,1726,,RH,870 7 AVENUE,225,...,0,0,1,0,0,1925,4,R5,13047,2012-08-01 00:00:00
6161,1,HARLEM-CENTRAL,13 CONDOS - ELEVATOR APARTMENTS,2,1830,1102,,R4,266 WEST 115 STREET,1B,...,1,0,1,0,0,2005,2,R4,650000,2012-08-01 00:00:00
25248,1,UPPER WEST SIDE (79-96),07 RENTALS - WALKUP APARTMENTS,2B,1229,34,,C7,450 AMSTERDAM AVENUE,,...,8,2,10,2175,9250,1910,2,C7,12375000,2012-08-01 00:00:00
8822,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1333,23,,D4,"5 TUDOR CITY PLACE, 1728",,...,0,0,0,0,0,1930,2,D4,265000,2012-08-01 00:00:00
25694,1,UPPER WEST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1243,8,,D4,"255 WEST 95TH STREET, 2A",,...,0,0,0,0,0,1908,2,D4,740000,2012-08-01 00:00:00
8821,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1333,23,,D4,"5 TUDOR CITY PLACE, 2020",,...,0,0,0,0,0,1930,2,D4,440000,2012-08-01 00:00:00
24703,1,UPPER WEST SIDE (59-79),13 CONDOS - ELEVATOR APARTMENTS,2,1171,3178,,R4,120 RIVERSIDE BOULEVARD,11M,...,1,0,1,0,0,0,2,R4,765000,2012-08-01 00:00:00
13786,1,MIDTOWN WEST,13 CONDOS - ELEVATOR APARTMENTS,2,1049,1043,,R4,25 COLUMBUS CIRCLE,ST56F,...,1,0,1,0,0,1955,2,R4,3800000,2012-08-01 00:00:00
4693,1,GREENWICH VILLAGE-CENTRAL,13 CONDOS - ELEVATOR APARTMENTS,2,558,1216,,R4,125 EAST 12TH STREET,2-H,...,1,0,1,0,0,0,2,R4,1100000,2012-08-01 00:00:00
23440,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1121,29,,D4,"80 CENTRAL PARK WEST, 7B",,...,0,0,0,0,0,1968,2,D4,761500,2012-08-01 00:00:00
16686,1,MURRAY HILL,10 COOPS - ELEVATOR APARTMENTS,2,916,61,,D4,"200 EAST 36TH STREET, 12-A",,...,0,0,0,0,0,1955,2,D4,328000,2012-08-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4122,1,GRAMERCY,17 CONDOPS,2,874,1003,,R9,"157 EAST 18TH STREET, 5J",,...,0,0,0,0,0,0,2,R9,660000,2013-08-15 00:00:00
7935,1,LOWER EAST SIDE,13 CONDOS - ELEVATOR APARTMENTS,2,350,1013,,R4,20 CLINTON STREET,5A,...,1,0,1,0,0,0,2,R4,450000,2013-08-15 00:00:00
19641,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1472,14,,D4,"435 EAST 77TH STREET, 12D",,...,0,0,0,0,0,1962,2,D4,367500,2013-08-15 00:00:00
16410,1,MURRAY HILL,10 COOPS - ELEVATOR APARTMENTS,2,864,35,,D4,"10 PARK AVENUE, 15A",,...,0,0,0,0,0,1932,2,D4,1735000,2013-08-15 00:00:00
6851,1,HARLEM-UPPER,09 COOPS - WALKUP APARTMENTS,2,2066,51,,C6,"450 WEST 152 STREET, 24",,...,0,0,0,0,0,1906,2,C6,135540,2013-08-15 00:00:00
2236,1,EAST VILLAGE,10 COOPS - ELEVATOR APARTMENTS,2,466,56,,D4,"103 EAST 10TH STREET, 3C",,...,0,0,0,0,0,1920,2,D4,645000,2013-08-15 00:00:00
19339,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1439,1,,D4,"301 EAST 64TH STREET, 11K",,...,0,0,0,0,0,1963,2,D4,372500,2013-08-15 00:00:00
1660,1,CLINTON,09 COOPS - WALKUP APARTMENTS,2,1054,24,,C6,"411 WEST 44TH STREET, 22",,...,0,0,0,0,0,1920,2,C6,480000,2013-08-15 00:00:00
26558,1,UPPER WEST SIDE (96-116),10 COOPS - ELEVATOR APARTMENTS,2,1891,35,,D4,"325 RIVERSIDE DRIVE, 2",,...,0,0,0,0,0,1920,2,D4,1150000,2013-08-15 00:00:00
27259,1,WASHINGTON HEIGHTS UPPER,10 COOPS - ELEVATOR APARTMENTS,2,2180,450,,D4,"100 OVERLOOK TERRACE, 617",,...,0,0,0,0,0,1963,2,D4,333000,2013-08-15 00:00:00
8122,1,MANHATTAN VALLEY,10 COOPS - ELEVATOR APARTMENTS,2,1841,52,,D4,"50 WEST 106TH STREET, 12B",,...,0,0,0,0,0,1930,2,D4,420000,2013-08-15 00:00:00
21131,1,UPPER EAST SIDE (79-96),09 COOPS - WALKUP APARTMENTS,2,1562,38,,C6,"416 EAST 83RD STREET, 2A",,...,0,0,0,0,0,1930,2,C6,292500,2013-08-15 00:00:00
21976,1,UPPER EAST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1559,10,,D4,"425 EAST 79TH STREET, 5N",,...,0,0,0,0,0,1955,2,D4,575000,2013-08-15 00:00:00
25472,1,UPPER WEST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1207,34,,D4,"336 CENTRAL PARK WEST, 14B",,...,0,0,0,0,0,1929,2,D4,3300000,2013-08-15 00:00:00
9259,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1365,20,,D4,"60 SUTTON PLACE SOUTH, 5LS",,...,0,0,0,0,0,1951,2,D4,365000,2013-08-16 00:00:00
26804,1,UPPER WEST SIDE (96-116),17 CONDOPS,2,1883,1002,,R9,"545 WEST 111TH STREET, 6N",,...,0,0,0,0,0,1930,2,R9,399000,2013-08-16 00:00:00
524,1,CHELSEA,10 COOPS - ELEVATOR APARTMENTS,2,797,76,,D4,"166 WEST 22ND STREET, 2A",,...,0,0,0,0,0,1950,2,D4,749000,2013-08-16 00:00:00
25047,1,UPPER WEST SIDE (59-79),17 CONDOPS,2,1158,1405,,R9,"170 WEST END AVENUE, PSR-19",,...,0,0,0,0,0,1965,2,R9,60000,2013-08-16 00:00:00
20543,1,UPPER EAST SIDE (59-79),13 CONDOS - ELEVATOR APARTMENTS,2,1484,1125,,R4,515 EAST 72ND STREET,11E,...,1,0,1,0,0,1985,2,R4,692410,2013-08-16 00:00:00
22814,1,UPPER EAST SIDE (79-96),15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,1513,1603,,R1,157 EAST 84TH STREET,2,...,1,0,1,0,0,0,2,R1,8850000,2013-08-16 00:00:00
1411,1,CIVIC CENTER,10 COOPS - ELEVATOR APARTMENTS,2,117,1,,D4,"165 PARK ROW, 2F",,...,0,0,0,0,0,1960,2,D4,856000,2013-08-16 00:00:00
23543,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1126,14,,D4,"23 WEST 73RD STREET, 1111",,...,0,0,0,0,0,1926,2,D4,825000,2013-08-16 00:00:00
13045,1,MIDTOWN WEST,10 COOPS - ELEVATOR APARTMENTS,2,1030,29,,D4,"200 CENTRAL PARK SOUTH, 5B",,...,0,0,0,0,0,1963,2,D4,4350000,2013-08-19 00:00:00
20806,1,UPPER EAST SIDE (59-79),17 CONDOPS,2,1458,1202,,R9,"420 EAST 64 STREET, W 10K",,...,0,0,0,0,0,0,2,R9,467896,2013-08-19 00:00:00
9260,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1365,20,,D4,"60 SUTTON PLACE SOUTH, 3BN",,...,0,0,0,0,0,1951,2,D4,815000,2013-08-19 00:00:00
3559,1,FLATIRON,17 CONDOPS,2,821,1202,,R9,"32 WEST 20TH STREET, 6N",,...,0,0,0,0,0,1912,2,R9,2199000,2013-08-19 00:00:00
4585,1,GREENWICH VILLAGE-CENTRAL,10 COOPS - ELEVATOR APARTMENTS,2,576,1,,D4,"79 WEST 12TH STREET, 2B",,...,0,0,0,0,0,1960,2,D4,655000,2013-08-20 00:00:00
18978,1,UPPER EAST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1406,50,,D4,"160 EAST 72ND STREET, 5 FLR",,...,0,0,0,0,0,1928,2,D4,8678250,2013-08-21 00:00:00
22388,1,UPPER EAST SIDE (79-96),13 CONDOS - ELEVATOR APARTMENTS,,1517,1169,,,141 EAST 88TH STREET,,...,0,0,0,0,0,0,2,R4,8527106,2013-08-23 00:00:00
22452,1,UPPER EAST SIDE (79-96),13 CONDOS - ELEVATOR APARTMENTS,2,1527,1134,,R4,215 EAST 81ST STREET,7F,...,1,0,1,0,0,0,2,R4,585000,2013-08-23 00:00:00

In [52]:
grouped1 = df4.groupby(['SALE DATE', 'BUILDING CLASS AT TIME OF SALE'])

In [53]:
grouped1['SALE\nPRICE'].sum()

SALE DATE   BUILDING CLASS AT TIME OF SALE
2012-08-01  C1                                  8050010
            C3                                       10
            C6                                   704646
            C7                                 12375000
            D4                                 42195000
            K2                                  5000035
            R1                                  6455010
            R4                                 32656415
            R5                                   206193
            R8                                  1545375
            R9                                  4532500
            S2                                   635000
            S3                                  1050000
2012-08-02  A7                                  6250000
            A9                                  2250000
            B1                                  8900000
            C6                                  1700000
            C7                                  7000000
            D4                                 31236395
            K9                                  4250000
            R2                                  1002500
            R4                                 43854320
            R5                                  2520000
            R9                                  2718500
            RR                                  9870001
            S4                                  3000000
2012-08-03  C5                                   635000
            C6                                   270000
            C7                                  4500000
            D4                                  4886097
                                                ...
2013-08-12  D4                                 25602092
            R2                                   473000
            R4                                  2160000
            R9                                   518000
2013-08-13  B3                                  5190000
            C1                                        1
            C6                                  3580000
            D0                                  1210000
            D4                                 12117161
            O3                                150000000
            R4                                  1770000
            R9                                   825000
2013-08-14  C6                                   727000
            D0                                   500000
            D4                                 25169000
            R4                                  1760000
            R9                                  1925000
2013-08-15  C6                                   908040
            D4                                 25735500
            R4                                   450000
            R9                                   660000
2013-08-16  D4                                  2795000
            R1                                  8850000
            R4                                   692410
            R9                                   459000
2013-08-19  D4                                  5165000
            R9                                  2666896
2013-08-20  D4                                   655000
2013-08-21  D4                                  8678250
2013-08-23  R4                                  9112106
Name: SALE\nPRICE, Length: 3161, dtype: int64

In [57]:
grouped2 = df4.groupby(['BUILDING CLASS AT TIME OF SALE'])
grouped2['SALE\nPRICE'].sum().sort_values(ascending=False)

BUILDING CLASS AT TIME OF SALE
R4    10166896953
D4     7964662223
O3     3516158615
R5     2691486644
O4     1781000000
C7     1555514487
O9     1411527413
RK     1102847659
O2     1077247440
RR      919451033
R9      912955863
K9      880175984
R1      813936446
RH      719818493
L2      716029852
L8      692810679
D8      660500000
C1      639770971
V1      601190531
D1      586566496
D9      570598229
A4      525306319
H2      524820162
C6      493715969
D0      482554099
RB      439691706
D6      439007936
C5      434015632
L9      425350462
H3      412621000
         ...
F1       38350000
I9       35000000
RG       32277642
RW       27170168
G5       25865764
M2       24500000
N2       21800000
R6       21296262
D5       21276160
O8       19405500
A0       15500000
D2       11325000
Z5       11140000
E1       11100000
C8       10374000
B2        9115000
G4        7000000
F9        5183000
R3        5002525
M3        5000000
RA        4389800
M9        4036040
W8        3800000
C9        2394000
E3        2375000
RS        1983668
F5        1800000
A1        1040000
P8         765000
S0         526000
Name: SALE\nPRICE, Length: 105, dtype: int64